name: Daily File Push Simple

on:
  schedule:
    - cron: '0 9 * * *'
  workflow_dispatch:
    inputs:
      day_override:
        description: 'Override day number (1-70)'
        required: false
        type: string

jobs:
  daily-push:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 0
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: Calculate current day
      id: calculate-day
      run: |
        START_DATE="2025-10-25"
        START_TIMESTAMP=$(date -d "$START_DATE" +%s)
        CURRENT_TIMESTAMP=$(date +%s)
        DAYS_DIFF=$(( (CURRENT_TIMESTAMP - START_TIMESTAMP) / 86400 + 1 ))
        
        if [ -n "${{ github.event.inputs.day_override }}" ]; then
          DAYS_DIFF="${{ github.event.inputs.day_override }}"
        fi
        
        if [ $DAYS_DIFF -lt 1 ]; then
          DAYS_DIFF=1
        elif [ $DAYS_DIFF -gt 70 ]; then
          DAYS_DIFF=70
        fi
        
        echo "day=$DAYS_DIFF" >> $GITHUB_OUTPUT
        echo "Calculated day: $DAYS_DIFF"
    
    - name: Test step
      run: |
        echo "Workflow is running for day ${{ steps.calculate-day.outputs.day }}"
        echo "Files in repository:"
        ls -la
